services:
  db:
    image: postgres:16-alpine
    ports:
      - "5434:5432"
    environment:
      POSTGRES_DB: geosim
      POSTGRES_USER: geosim
      POSTGRES_PASSWORD: geosim
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  pgdata:
